fastlane_version "2.7.0"
default_platform :ios

platform :ios do
    
    before_all do |lane, options|
        ensure_git_status_clean                                
    end

    lane :test do
        scan
    end
    
    lane :lint do
        swiftlint(mode: :autocorrect)
        repo_clean = `git status --porcelain`.empty?
        if repo_clean
            UI.success('Code is clean, all good! 💪')        
        else
            git_commit(path: ".", message: "Fix style with SwiftLint")
            push_to_git_remote
        end
    end
    
end